kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      "feature-gates": "EndpointSlice=true"
      "runtime-config": "discovery.k8s.io/v1alpha1=true"
  controllerManager:
    extraArgs:
      "controllers": "*,endpointslice"
