apiVersion: v1
kind: Service
metadata:
  labels:
    app: pilot-proxy
  name: istio-pilot-proxy
  namespace: istio-system
spec:
  ports:
    - name: grpc-xds
      port: 15020
      protocol: TCP
      targetPort: 15020
  selector:
    istio: pilot-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-pilot-proxy
  namespace: istio-system
  labels:
    istio: pilot-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      istio: pilot-proxy
  template:
    metadata:
      labels:
        istio: pilot-proxy
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: istio-proxy
        image: gcr.io/howardjohn-istio/proxyv2:1565308420
        args:
        - proxy
        - --domain
        - $(POD_NAMESPACE).svc.cluster.local
        - --serviceCluster
        - istio-pilot-proxy
        - --templateFile
        - /etc/istio/proxy/envoy_proxy.yaml.tmpl
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        ports:
        - containerPort: 15020
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
