apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell
  namespace: default
spec:
  selector:
    matchLabels:
      app: shell
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.istio.io/interceptionMode: REDIRECT
        sidecar.istio.io/status: '{"version":"a5a7eeb1b660831e5e89597040a60898e0d13455aa8cde903c583af25c8434f6","initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-certs"],"imagePullSecrets":null}'
        traffic.sidecar.istio.io/excludeInboundPorts: "15020"
        traffic.sidecar.istio.io/includeOutboundIPRanges: '*'
      labels:
        app: shell
    spec:
      containers:
        - args:
            - proxy
            - sidecar
            - --domain
            - $(POD_NAMESPACE).svc.cluster.local
            - --configPath
            - /etc/istio/proxy
            - --binaryPath
            - /usr/local/bin/envoy
            - --serviceCluster
            - shell.$(POD_NAMESPACE)
            - --drainDuration
            - 45s
            - --parentShutdownDuration
            - 1m0s
            - --discoveryAddress
            - istio-pilot-proxy.istio-system:15020
            - --zipkinAddress
            - zipkin.istio-system:9411
            - --dnsRefreshRate
            - 300s
            - --connectTimeout
            - 10s
            - --proxyAdminPort
            - "15000"
            - --concurrency
            - "2"
            - --controlPlaneAuthPolicy
            - NONE
            - --statusPort
            - "15020"
            - --applicationPorts
            - ""
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ISTIO_META_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ISTIO_META_CONFIG_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ISTIO_META_INTERCEPTION_MODE
              value: REDIRECT
            - name: ISTIO_META_INCLUDE_INBOUND_PORTS
            - name: ISTIO_METAJSON_LABELS
              value: |
                {"app":"shell"}
          image: gcr.io/istio-release/proxyv2:master-20190807-09-16
          imagePullPolicy: IfNotPresent
          name: istio-proxy
          ports:
            - containerPort: 15090
              name: http-envoy-prom
              protocol: TCP
          readinessProbe:
            failureThreshold: 30
            httpGet:
              path: /healthz/ready
              port: 15020
            initialDelaySeconds: 1
            periodSeconds: 2
          resources:
            limits:
              cpu: "2"
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 128Mi
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 1337
          volumeMounts:
            - mountPath: /etc/istio/proxy
              name: istio-envoy
            - mountPath: /etc/certs/
              name: istio-certs
              readOnly: true
      initContainers:
        - args:
            - -p
            - "15001"
            - -z
            - "15006"
            - -u
            - "1337"
            - -m
            - REDIRECT
            - -i
            - '*'
            - -x
            - ""
            - -b
            - ""
            - -d
            - "15020"
          image: gcr.io/istio-release/proxy_init:master-20190807-09-16
          imagePullPolicy: IfNotPresent
          name: istio-init
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 10Mi
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            runAsNonRoot: false
            runAsUser: 0
      volumes:
        - emptyDir:
            medium: Memory
          name: istio-envoy
        - name: istio-certs
          secret:
            optional: true
            secretName: istio.default